# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-slim

WORKDIR /app

# Copy package manifests
COPY package*.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy remaining source code
COPY . .

# Run build script to ensure entrypoint is executable
RUN npm run build

EXPOSE 3000

CMD [ "npm", "start" ]
